"""add_region

Revision ID: 1b2902bd6ab4
Revises: 0d1ddae64fa1
Create Date: 2026-06-04 16:28:59.241690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b2902bd6ab4'
down_revision: Union[str, Sequence[str], None] = '0d1ddae64fa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('convocatorias', sa.Column('region', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('convocatorias', 'region')
    # ### end Alembic commands ###
