"""final_clean_schema

Revision ID: 5216e1490621
Revises: 
Create Date: 2026-06-02 13:36:38.293029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5216e1490621'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_notificaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('configuracion', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('activa', sa.BOOLEAN(), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuentes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('url_base', sa.String(length=500), nullable=False),
    sa.Column('configuracion_yaml', sa.Text(), nullable=False),
    sa.Column('activa', sa.BOOLEAN(), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fuente_id', sa.UUID(), nullable=True),
    sa.Column('nivel', sa.String(length=20), nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('detalles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fuente_id'], ['fuentes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('convocatorias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fuente_id', sa.UUID(), nullable=False),
    sa.Column('identificador_externo', sa.String(length=255), nullable=False),
    sa.Column('titulo', sa.String(length=500), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('url_detalle', sa.String(length=500), nullable=False),
    sa.Column('fecha_apertura', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('fecha_cierre', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('monto', sa.NUMERIC(precision=15, scale=2), nullable=True),
    sa.Column('estado', sa.String(length=100), nullable=False),
    sa.Column('metadatos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fuente_id'], ['fuentes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fuente_id', sa.UUID(), nullable=False),
    sa.Column('fecha_captura', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('contenido_crudo', sa.Text(), nullable=False),
    sa.Column('hash_contenido', sa.String(length=64), nullable=False),
    sa.Column('estado_ejecucion', sa.String(length=50), nullable=False),
    sa.Column('metadatos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['fuente_id'], ['fuentes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_cambios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('convocatoria_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('fecha_deteccion', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('es_apertura', sa.BOOLEAN(), nullable=False),
    sa.Column('delta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('es_relevante', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['convocatoria_id'], ['convocatorias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('historial_cambios_id', sa.UUID(), nullable=False),
    sa.Column('canal', sa.String(length=50), nullable=False),
    sa.Column('destinatario', sa.String(length=255), nullable=False),
    sa.Column('enviado_en', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['historial_cambios_id'], ['historial_cambios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificaciones')
    op.drop_table('historial_cambios')
    op.drop_table('snapshots')
    op.drop_table('convocatorias')
    op.drop_table('audit_logs')
    op.drop_table('fuentes')
    op.drop_table('config_notificaciones')
    # ### end Alembic commands ###
