"""add_suscripciones

Revision ID: ac1808e99240
Revises: e5916eb1bd6f
Create Date: 2026-06-19 21:59:14.695039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac1808e99240'
down_revision: Union[str, Sequence[str], None] = 'e5916eb1bd6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suscripciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('regiones', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('activa', sa.BOOLEAN(), nullable=False),
    sa.Column('token_confirmacion', sa.String(length=100), nullable=True),
    sa.Column('confirmado', sa.BOOLEAN(), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suscripciones_chat_id'), 'suscripciones', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suscripciones_chat_id'), table_name='suscripciones')
    op.drop_table('suscripciones')
    # ### end Alembic commands ###
