"""add_screenshot_b64_to_snapshots

Revision ID: e5916eb1bd6f
Revises: 1b2902bd6ab4
Create Date: 2026-06-19 18:57:07.286763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5916eb1bd6f'
down_revision: Union[str, Sequence[str], None] = '1b2902bd6ab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snapshots', sa.Column('screenshot_b64', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snapshots', 'screenshot_b64')
    # ### end Alembic commands ###
